title: "Shannon Froese"
description: "Database Administrator 路 Automation Architect 路 Bridging business and technology through data-driven solutions."
baseurl: "" # leave empty unless your site is in a subfolder
url: "https://safroese.github.io" # replace with your GitHub Pages URL

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-include-cache

# Optional settings
markdown: kramdown
highlighter: rouge

# Author info (optional)
author:
  name: "Shannon Froese"
  avatar: "/assets/images/headshot.jpg"
  bio: "Database Administrator 路 Automation Architect 路 Bridging business and technology through data-driven solutions."

# Social links (optional)
social:
  type: person
  links:
    - https://www.linkedin.com/in/shannonafroese
    - https://github.com/safroese

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
  - scope:
      path: ""
      type: posts
    values:
      layout: single

include:
  - _data
  - _includes
  - _sass
  - _pages

atom_feed:
  hide: true
